name: CICD

on:
  workflow_dispatch:
    inputs:
      service:
        options:
          - all
          - api
          - cms
        required: true
        type: choice
        description: Choose which service to run

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
        
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx

    # Build and push CMS image if the selected service is "cms" or "all"
    - name: Build and Push CMS
      if: ${{ github.event.inputs.service == 'cms' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_cms
      with:
        context: ./ServiceStackBaseCms.Client/
        file: ./ServiceStackBaseCms.Client/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:cms

    # Build and push API image if the selected service is "api" or "all"
    - name: Build and Push API
      if: ${{ github.event.inputs.service == 'api' || github.event.inputs.service == 'all' }}
      uses: docker/build-push-action@v2
      id: docker_build_api
      with:
        context: ./ServiceStackBaseCms/
        file: ./ServiceStackBaseCms/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gmobile:api

    # Verification step for CMS
    - name: Verify CMS
      if: ${{ github.event.inputs.service == 'cms' || github.event.inputs.service == 'all' }}
      run: echo ${{ steps.docker_build_cms.outputs.digest }}_cms

    # Verification step for API
    - name: Verify API
      if: ${{ github.event.inputs.service == 'api' || github.event.inputs.service == 'all' }}
      run: echo ${{ steps.docker_build_api.outputs.digest }}_api
